# Generated by Django 4.1.2 on 2022-10-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cases', '0002_solutions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_scene', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('criminal_record', models.IntegerField()),
                ('finger_prints', models.CharField(max_length=5)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Responsible_officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.IntegerField()),
                ('rank', models.CharField(max_length=20)),
                ('full_name', models.CharField(max_length=20)),
                ('officer_address', models.CharField(max_length=20)),
                ('family_composition', models.CharField(max_length=10)),
            ],
        ),
    ]
