# Generated by Django 4.1.2 on 2022-10-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cases', '0003_incident_information_participants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident_information',
            name='description',
            field=models.TextField(verbose_name='описание случившегося'),
        ),
        migrations.AlterField(
            model_name='incident_information',
            name='incident_scene',
            field=models.TextField(verbose_name='адрес места происшествия'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='incident_type',
            field=models.CharField(max_length=15, verbose_name='Тип происшествия'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='message_sourse',
            field=models.CharField(max_length=15, verbose_name='Кто сообщил'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='when',
            field=models.DateTimeField(verbose_name='Дата происшествия'),
        ),
        migrations.AlterField(
            model_name='participants',
            name='address',
            field=models.CharField(max_length=20, verbose_name='Адрес участника происшествия'),
        ),
        migrations.AlterField(
            model_name='participants',
            name='criminal_record',
            field=models.IntegerField(verbose_name='Количество судимостей участника'),
        ),
        migrations.AlterField(
            model_name='participants',
            name='finger_prints',
            field=models.CharField(max_length=5, verbose_name='Наличие в базе отпечатков пальцев'),
        ),
        migrations.AlterField(
            model_name='participants',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Участник происшествия'),
        ),
        migrations.AlterField(
            model_name='participants',
            name='status',
            field=models.CharField(max_length=10, verbose_name='Статус участника'),
        ),
        migrations.AlterField(
            model_name='responsible_officer',
            name='certificate_number',
            field=models.IntegerField(verbose_name='Номер удостоверения'),
        ),
        migrations.AlterField(
            model_name='responsible_officer',
            name='family_composition',
            field=models.CharField(max_length=10, verbose_name='Семейное положение ответственного лица'),
        ),
        migrations.AlterField(
            model_name='responsible_officer',
            name='full_name',
            field=models.CharField(max_length=20, verbose_name='ФИО ответственного лица'),
        ),
        migrations.AlterField(
            model_name='responsible_officer',
            name='officer_address',
            field=models.CharField(max_length=20, verbose_name='Адрес ответственного лица'),
        ),
        migrations.AlterField(
            model_name='responsible_officer',
            name='rank',
            field=models.CharField(max_length=20, verbose_name='Звание'),
        ),
        migrations.AlterField(
            model_name='solutions',
            name='result',
            field=models.CharField(max_length=15, verbose_name='Решение по делу'),
        ),
    ]
